# Generated by Django 2.2.4 on 2019-08-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30, verbose_name='푸드트럭명')),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('category', models.CharField(choices=[('치킨', '치킨'), ('햄버거', '햄버거')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
