# Generated by Django 2.2.4 on 2019-08-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masteruser',
            old_name='name',
            new_name='username',
        ),
    ]
