# Generated by Django 2.2.4 on 2019-08-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190809_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='master',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
