# Generated by Django 2.2.4 on 2019-08-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='foodtruck',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.FoodTruck'),
            preserve_default=False,
        ),
    ]
